version: "2.0"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.j
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
            MYSQL_ROOT_PASSWORD: WeShallThis
            MYSQL_DATABASE: voting_app
            MYSQL_USER: vincent
            MYSQL_PASSWORD: AllInFountainPen
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
